version: "3.9"

networks:
  hack:


services:
  auth-client:
    container_name: auth-client
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - hack
