version: '3.5'

networks:
  hack:

services:
  hack_backend:
    container_name: hack_back
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENV=docker
    ports:
      - "8080:8080"
    networks:
      - hack